service:
  port: 8084

extraEnv:
- name: SERVER_PORT
  value: "8084"
- name: SPRING_DATASOURCE_URL
  value: jdbc:postgresql://postgres-postgresql.demo-postgres.svc.cluster.local:5432/postgres
- name: SPRING_DATASOURCE_USERNAME
  value: postgres
- name: SPRING_DATASOURCE_PASSWORD
  value: MyTopSecretPassword  
- name: MANAGEMENT_SERVER_PORT
  value: "8081"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: reader.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - reader.127.0.0.1.nip.io
