apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-challenge
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: solution/argocd-apps
    repoURL: https://github.com/hajnej/sre-challenge
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
