apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/hajnej/sre-challenge.git'
    path: solution/helm/charts/reader
    targetRevision: HEAD
    helm:
      releaseName: reader
      values: |-
        image:
          repository: hajney/reader
        service:
          port: 8084

        extraEnv:
        - name: SERVER_PORT
          value: "8084"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-postgresql.demo-postgres.svc.cluster.local:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: MyTopSecretPassword  
        - name: MANAGEMENT_SERVER_PORT
          value: "8081"

        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: reader.127.0.0.1.nip.io
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
          - secretName: tls-cert
            hosts:
            - reader.127.0.0.1.nip.io

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-reader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
